### ISSUE TITLE
libnss-mysql compatible configuration

### ISSUE THREAD

**Issue by ondrejj** [istana/libnss-maria#10]
Please, can you add an libnss-mysql compatible configuration? I am preparing an centos/fedora package and it would be useful to have also compatibility configuration. Attaching an example configuration.
[libnss-maria.conf.txt](https://github.com/istana/libnss-maria/files/5627753/libnss-maria.conf.txt)

**Comment by ondrejj** [comment]
There is an mistake in my previous version, attaching new one. Changed getgrgid WHERE condition.
[libnss-maria.conf.txt](https://github.com/istana/libnss-maria/files/5634245/libnss-maria.conf.txt)

**Comment by istana** [comment]
Sure. Is the config file compatible with "linux" example? https://github.com/saknopper/libnss-mysql/tree/master/sample/linux

**Comment by ondrejj** [comment]
Yes.

**Comment by istana** [comment]
I added example configuration and integration test, should be fine now

**Comment by ondrejj** [comment]
Thanks, but "unix_socket = "/var/lib/mysql/mysql.sock";" is needed in my configuration. This is default for libnss-mysql. Can you please add it?

**Comment by istana** [comment]
I added unix_socket entry into config

**Comment by istana** [comment]
please reopen if I missed something else
