### ISSUE TITLE
Too many open files when browsing filesystems (find command)

### ISSUE THREAD

**Issue by ondrejj** [istana/libnss-maria#11]
Using a "find /home -nouser" command on a filesystem with many files, there is "Too many files" error displayed.

```
opening file failed, file=/etc/libnss-maria.conf, error number=24, error description=Too many open filesplaceholder not found in database query, _nss_maria_getpwuid_r/home/user/x/apps
find: '/home/user/x/apps': Too many open files
```

**Comment by Cyborgscode** [comment]
a quicktest on my system did not reproduce this issue.

**Comment by istana** [comment]
Could you share more details - operating system and version and how many files are in /home directory? I also couldn't reproduce it in Debian Buster with thousands of files.

**Comment by ondrejj** [comment]
Using my own package on CentOS 8. Planning to add this package as official package in Fedora/CentOS/RHEL.

Not so much files on /home, 396944 files according to df -i (i-nodes). Aproximately 350 users in SQL. Most files has one group only from SQL.

Switching to libnss-mysql fixes this problem, switch back to maria, problem present again.

In /proc/PID/fd I see this:

```
lr-x------. 1 root root 64 dec  4 11:11 90 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 91 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 92 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 93 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 94 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 95 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 96 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 97 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 98 -> /etc/libnss-maria.conf
lr-x------. 1 root root 64 dec  4 11:11 99 -> /etc/libnss-maria.conf
and many more
```

Looks like libnss-maria.conf is not closed properly.

**Comment by ondrejj** [comment]
Here is link to my package, if someone want to try:
http://www.salstar.sk/pub/fedora/testing/33/x86_64/libnss-maria-0.92-2.fc33.x86_64.rpm
http://www.salstar.sk/pub/fedora/testing/33/SRPMS/libnss-maria-0.92-2.fc33.src.rpm

Includes also authselect configuration to easy install/switch between auth methods.

**Comment by istana** [comment]
should be fixed now, please test

**Comment by ondrejj** [comment]
Works well. Thanks.
