### ISSUE TITLE
Memory leak in maria_config_helpers.c

### ISSUE THREAD

**Issue by bassbot123** [istana/libnss-maria#18]
Hello, 

First of all, thanks for putting this all together, it has served me well so far.

A memory leak was found on my host Ubuntu 20.04 system, spotted with a bizarre increase in swap space up to around 400mb over a period of time.

With analysis using Valgrind, a memory leak was found losing around 16k bytes, 1024 bytes at a time (from the malloc below) 
`config_lookup_string` doesn't need to take a memory allocated parameter. The leak most likely happened because memory was allocated inside the config struct, and only the struct was freed leaving a trail of memory unhandled.

https://github.com/istana/libnss-maria/blob/be5efd71acc65141eb3ec60ef429c7d820abf387/src/configuration/maria_config_helpers.c#L20

To replicate this, I wrote a hacky C script to plug into `_nss_maria_getpwnam_r`, then compiled it and ran it against Valgrind. For a given mariadb user account, e.g. testgroup in this case, Valgrind highlighted the leak. 

```#include <stdio.h>
#include <stdlib.h>
#include <nss.h>
#include <pwd.h>

extern enum nss_status _nss_maria_getpwnam_r (
		const char *name, 
		struct passwd *result_buf, 
		char *buffer, 
		size_t buflen, 
		int *errnop, 
	        int *h_errnop
);


int main() {
   printf("Running check for leaks\n");

   const char *accounts[] = { "testgroup" };
   struct passwd *result;
   size_t buflen = 1024;
   char buffer[buflen];
   int num = 2;
   int *numP = &num;
   int nssResult;
   result = (struct passwd *) malloc(sizeof(struct passwd));
   
   size_t i = 0;
   for ( i = 0; i < sizeof(accounts) / sizeof(accounts[0]); i++){
       nssResult = _nss_maria_getpwnam_r(accounts[i], result, buffer, buflen, numP, numP);
       printf("_nss_maria_getpwnam_r result = %d\n", nssResult);
   }
   free(result);
}
```

I then removed the malloc and replaced it with a `const char *` and Valgrind then detected no leaks. It might be worth digging into other methods to see memory leaks occur, but I haven't experienced any other untoward behaviour. 

I don't have access to create branches, but here is the proposed change:

```
void maria_load_string_setting(config_t libconfig_object, char *destination, const char *selector) {
  const char *buffer;

  if(config_lookup_string(&libconfig_object, selector, &buffer) == CONFIG_TRUE) {
  ...
```

**Comment by istana** [comment]
Hi, thanks for reporting the issue. There is a way if you would like to fix it. On the top right there is a "Fork" button which creates a copy of the repo in your account and then a pull request can be created against this repo. Otherwise I'll investigate sometimes in next few days.

**Comment by istana** [comment]
Should be fixed now, please reopen if there are any problems. I misunderstood the documentation, malloc was indeed not necessary.
