### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Rod2012** [istana/libnss-maria#20]
Running the script ./scripts/build-debug.sh I got this error message:

cp: cannot stat '/home/libnss-maria/examples/sos-sso/nsswitch.conf': No such file or directory

I saw that the variable HOME_PATH in the compile_and_test.sh file is (line 5)

`HOME_PATH="/home/libnss-maria"`

but it is not used when cp command is running (eg. line 46)
`$SUDO_COMMAND cp -bf /home/libnss-maria/examples/$EXAMPLE_SET/nsswitch.conf /etc`

why not
`$SUDO_COMMAND cp -bf ${HOME_PATH}/examples/$EXAMPLE_SET/nsswitch.conf /etc`
?

**Comment by istana** [comment]
Hi, I replaced hardcoded paths with HOME_PATH variable. Also updated README a bit since it may be risky to run integration tests on real system.

Please reopen if there are any issues.
