### ISSUE TITLE
Problem with replace() code from stackoverflow

### ISSUE THREAD

**Issue by Cyborgscode** [istana/libnss-maria#5]
Hi,

the while ( --count ) () Loop contains code, that could lead to a race condition while executed. 

the strstr() in the for-loop is used internally in conjunction with a conditional break on the pointer returned,
but that check is missing in the while-loop part, assuming that the content of the to be replaced string did not change. 

You wanne use this routine in an secure environment with heavyly parallel processes and threads without the usage of protecting guards => bad idea.

Two improvments: a) copy the src string in  temp buffer and do all ops on this buffer b) use conditional break on the result of strstr() too.  If a) is implemented, b) can be skipped. but b) alone is not secure enough for a lib used in root context. Please add a) as a protective meassure.

**Comment by Cyborgscode** [comment]
just for the ones reading this, here the routine in question:

https://stackoverflow.com/questions/779875/what-function-is-to-replace-a-substring-from-a-string-in-c

**Comment by istana** [comment]
Hi, I have this one in todo list and hope to do it soon. Definitely in a couple of weeks.

**Comment by istana** [comment]
Should be ok now, please reopen or add new issue if you identify additional issues
